<form action="<?php echo Mage::getUrl('straightarrow_slickslider/adminhtml_index/save') ?>" method="post">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"  />
  <fieldset>
    <ul>
     <li>
       <label for="name">Name</label>
       <input type="text" id="name" name="name" />
     </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>
<?php echo $this->methodblock(); ?>